version: "3.8"
services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lifeness
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lifeness
    depends_on:
      - db

volumes:
  db:
    driver: local
